name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - run: go build ./cmd/os-bot
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          args: --timeout=5m
